rd ipch /s /q
rd Debug /s /q
rd Release /s /q
rd EllipsoMeter\Debug /s /q
rd EllipsoMeter\Release /s /q
rd .vs /s /q
del *.sdf /s /q
del *.VC.db /s /q
del *.VC.opendb /s /q
del EllipsoMeter\*.aps /s /q
